name: Daily Commit

on:
  schedule:
    - cron: "0 22 * * *"  # 6:00 AM PHT (10:00 PM UTC)
    - cron: "0 4 * * *"    # 12:00 PM PHT (4:00 AM UTC)
    - cron: "0 5 * * *"    # 1:00 PM PHT (5:00 AM UTC)
    - cron: "0 10 * * *"   # 6:00 PM PHT (10:00 AM UTC)
    
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}  # Use a PAT instead of GITHUB_TOKEN for contributions

      - name: Set up Git user
        run: |
          git config --global user.name "its-ryyt"
          git config --global user.email "expanderqwertz@gmail.com"

      - name: Update daily log file
        run: |
          echo "Last commit: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" > daily-log.txt

      - name: Commit and push changes
        run: |
          git add daily-log.txt
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "Automated commit: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
            git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/its-ryyt/its-ryyt.github.io.git main
          else
            echo "No changes to commit"
          fi
